// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD8BmoCNBXluvT10cLUkF5-ND857efJLts',
    appId: '1:458024576591:web:4ef1adfaca800f755bac3a',
    messagingSenderId: '458024576591',
    projectId: 'leafnlit',
    authDomain: 'leafnlit.firebaseapp.com',
    databaseURL: 'https://leafnlit-default-rtdb.firebaseio.com',
    storageBucket: 'leafnlit.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCH-pozzsEJX7KnmudPYG1OJ3GvtZu_0pw',
    appId: '1:458024576591:android:a6edfa0173ed20495bac3a',
    messagingSenderId: '458024576591',
    projectId: 'leafnlit',
    databaseURL: 'https://leafnlit-default-rtdb.firebaseio.com',
    storageBucket: 'leafnlit.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDI1b3SbZeS4oIyjXMz7CPvag0yLwp-TVs',
    appId: '1:458024576591:ios:492812617fb92fbd5bac3a',
    messagingSenderId: '458024576591',
    projectId: 'leafnlit',
    databaseURL: 'https://leafnlit-default-rtdb.firebaseio.com',
    storageBucket: 'leafnlit.appspot.com',
    iosBundleId: 'com.example.leafNLit',
  );

}